name: open_weather_api
description: A open weather api plugin for fetching current weather via the OpenWeatherMap API.
version: 0.0.1
homepage: https://github.com/cod3xpert/open_weather_api

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
